export const SET_DIARIES = 'SET_DIARIES';
export const SCOPE_DIARY = 'SCOPE_DIARY';
export const SET_SCOPED_DIARY_DAYS = 'SET_SCOPED_DIARY_DATES';
export const UPDATE_DAY = 'UPDATE_DAY';
export const ADD_WEEK_TO_SCOPE = 'ADD_WEEK_TO_SCOPE';
export const SCOPE_DAY = 'SCOPE_DAY';

export const SET_LOADING_DIARY = 'SET_LOADING_DIARY';
export const SET_SAVING_DIARY = 'SET_SAVING_DIARY';
export const ADD_DIARY = 'ADD_DIARY';
export const UPDATE_DIARY = 'UPDATE_DIARY';
export const FLUSH_DIARY_MODULE_STATE = 'FLUSH_DIARY_MODULE_STATE';
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';

export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

export const SET_SYNCHRONIZE_DIARIES_IN_PROGRESS = 'SET_SYNCHRONIZE_DIARIES_IN_PROGRESS';
export const SET_SYNCHRONIZE_NOTES_IN_PROGRESS = 'SET_SYNCHRONIZE_NOTES_IN_PROGRESS';