export const SET_CONTACTS = 'SET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const SCOPE_CONTACT = 'SCOPE_CONTACT';
export const SET_LOADING_CONTACTS_IN_PROGRESS = 'SET_LOADING_CONTACTS_IN_PROGRESS';